// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: service.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

// Actor carries the authenticated caller a mutation is attributed to: the
// principal id and the active account. On the Twirp surface the principal is
// overridden by the authenticated identity from the auth middleware; the
// account is taken from the request.
type Actor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Principal     string                 `protobuf:"bytes,1,opt,name=principal,proto3" json:"principal,omitempty"`
	Account       string                 `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Actor) Reset() {
	*x = Actor{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Actor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Actor) ProtoMessage() {}

func (x *Actor) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Actor.ProtoReflect.Descriptor instead.
func (*Actor) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *Actor) GetPrincipal() string {
	if x != nil {
		return x.Principal
	}
	return ""
}

func (x *Actor) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

type CheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Principal     string                 `protobuf:"bytes,2,opt,name=principal,proto3" json:"principal,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Object        string                 `protobuf:"bytes,4,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *CheckRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *CheckRequest) GetPrincipal() string {
	if x != nil {
		return x.Principal
	}
	return ""
}

func (x *CheckRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CheckRequest) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

type Decision struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Allow            bool                   `protobuf:"varint,1,opt,name=allow,proto3" json:"allow,omitempty"`
	Reason           string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	DecidingGrantIds []string               `protobuf:"bytes,3,rep,name=deciding_grant_ids,json=decidingGrantIds,proto3" json:"deciding_grant_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Decision) Reset() {
	*x = Decision{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decision) ProtoMessage() {}

func (x *Decision) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decision.ProtoReflect.Descriptor instead.
func (*Decision) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *Decision) GetAllow() bool {
	if x != nil {
		return x.Allow
	}
	return false
}

func (x *Decision) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Decision) GetDecidingGrantIds() []string {
	if x != nil {
		return x.DecidingGrantIds
	}
	return nil
}

type CheckBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queries       []*CheckRequest        `protobuf:"bytes,1,rep,name=queries,proto3" json:"queries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckBatchRequest) Reset() {
	*x = CheckBatchRequest{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckBatchRequest) ProtoMessage() {}

func (x *CheckBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckBatchRequest.ProtoReflect.Descriptor instead.
func (*CheckBatchRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *CheckBatchRequest) GetQueries() []*CheckRequest {
	if x != nil {
		return x.Queries
	}
	return nil
}

// BatchDecision is one aligned item of a batch result: either a decision or an
// error code+message for a per-item input-validation failure.
type BatchDecision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decision      *Decision              `protobuf:"bytes,1,opt,name=decision,proto3" json:"decision,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDecision) Reset() {
	*x = BatchDecision{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDecision) ProtoMessage() {}

func (x *BatchDecision) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDecision.ProtoReflect.Descriptor instead.
func (*BatchDecision) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *BatchDecision) GetDecision() *Decision {
	if x != nil {
		return x.Decision
	}
	return nil
}

func (x *BatchDecision) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *BatchDecision) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type CheckBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*BatchDecision       `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckBatchResponse) Reset() {
	*x = CheckBatchResponse{}
	mi := &file_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckBatchResponse) ProtoMessage() {}

func (x *CheckBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckBatchResponse.ProtoReflect.Descriptor instead.
func (*CheckBatchResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

func (x *CheckBatchResponse) GetResults() []*BatchDecision {
	if x != nil {
		return x.Results
	}
	return nil
}

type EnumerateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Principal     string                 `protobuf:"bytes,2,opt,name=principal,proto3" json:"principal,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Pattern       string                 `protobuf:"bytes,4,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumerateRequest) Reset() {
	*x = EnumerateRequest{}
	mi := &file_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumerateRequest) ProtoMessage() {}

func (x *EnumerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumerateRequest.ProtoReflect.Descriptor instead.
func (*EnumerateRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{7}
}

func (x *EnumerateRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *EnumerateRequest) GetPrincipal() string {
	if x != nil {
		return x.Principal
	}
	return ""
}

func (x *EnumerateRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *EnumerateRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *EnumerateRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type EnumerateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectIds     []string               `protobuf:"bytes,1,rep,name=object_ids,json=objectIds,proto3" json:"object_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumerateResponse) Reset() {
	*x = EnumerateResponse{}
	mi := &file_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumerateResponse) ProtoMessage() {}

func (x *EnumerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumerateResponse.ProtoReflect.Descriptor instead.
func (*EnumerateResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{8}
}

func (x *EnumerateResponse) GetObjectIds() []string {
	if x != nil {
		return x.ObjectIds
	}
	return nil
}

type EnumerateBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queries       []*EnumerateRequest    `protobuf:"bytes,1,rep,name=queries,proto3" json:"queries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumerateBatchRequest) Reset() {
	*x = EnumerateBatchRequest{}
	mi := &file_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumerateBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumerateBatchRequest) ProtoMessage() {}

func (x *EnumerateBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumerateBatchRequest.ProtoReflect.Descriptor instead.
func (*EnumerateBatchRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{9}
}

func (x *EnumerateBatchRequest) GetQueries() []*EnumerateRequest {
	if x != nil {
		return x.Queries
	}
	return nil
}

type BatchEnumeration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectIds     []string               `protobuf:"bytes,1,rep,name=object_ids,json=objectIds,proto3" json:"object_ids,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchEnumeration) Reset() {
	*x = BatchEnumeration{}
	mi := &file_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchEnumeration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchEnumeration) ProtoMessage() {}

func (x *BatchEnumeration) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchEnumeration.ProtoReflect.Descriptor instead.
func (*BatchEnumeration) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{10}
}

func (x *BatchEnumeration) GetObjectIds() []string {
	if x != nil {
		return x.ObjectIds
	}
	return nil
}

func (x *BatchEnumeration) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *BatchEnumeration) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type EnumerateBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*BatchEnumeration    `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumerateBatchResponse) Reset() {
	*x = EnumerateBatchResponse{}
	mi := &file_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumerateBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumerateBatchResponse) ProtoMessage() {}

func (x *EnumerateBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumerateBatchResponse.ProtoReflect.Descriptor instead.
func (*EnumerateBatchResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{11}
}

func (x *EnumerateBatchResponse) GetResults() []*BatchEnumeration {
	if x != nil {
		return x.Results
	}
	return nil
}

// ExplainResponse carries the engine Trace as canonical JSON (trace_json) — the
// recursive/nested derivation shape is not modelled in proto.
type ExplainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceJson     string                 `protobuf:"bytes,1,opt,name=trace_json,json=traceJson,proto3" json:"trace_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplainResponse) Reset() {
	*x = ExplainResponse{}
	mi := &file_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainResponse) ProtoMessage() {}

func (x *ExplainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainResponse.ProtoReflect.Descriptor instead.
func (*ExplainResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{12}
}

func (x *ExplainResponse) GetTraceJson() string {
	if x != nil {
		return x.TraceJson
	}
	return ""
}

type BatchTrace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceJson     string                 `protobuf:"bytes,1,opt,name=trace_json,json=traceJson,proto3" json:"trace_json,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchTrace) Reset() {
	*x = BatchTrace{}
	mi := &file_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchTrace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchTrace) ProtoMessage() {}

func (x *BatchTrace) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchTrace.ProtoReflect.Descriptor instead.
func (*BatchTrace) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{13}
}

func (x *BatchTrace) GetTraceJson() string {
	if x != nil {
		return x.TraceJson
	}
	return ""
}

func (x *BatchTrace) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *BatchTrace) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ExplainBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*BatchTrace          `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplainBatchResponse) Reset() {
	*x = ExplainBatchResponse{}
	mi := &file_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainBatchResponse) ProtoMessage() {}

func (x *ExplainBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainBatchResponse.ProtoReflect.Descriptor instead.
func (*ExplainBatchResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{14}
}

func (x *ExplainBatchResponse) GetResults() []*BatchTrace {
	if x != nil {
		return x.Results
	}
	return nil
}

// EntityRequest carries a mutation's actor plus the entity body as canonical
// JSON (the library's JSON encoding of the model.* struct).
type EntityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *Actor                 `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	EntityJson    string                 `protobuf:"bytes,2,opt,name=entity_json,json=entityJson,proto3" json:"entity_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityRequest) Reset() {
	*x = EntityRequest{}
	mi := &file_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityRequest) ProtoMessage() {}

func (x *EntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityRequest.ProtoReflect.Descriptor instead.
func (*EntityRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{15}
}

func (x *EntityRequest) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *EntityRequest) GetEntityJson() string {
	if x != nil {
		return x.EntityJson
	}
	return ""
}

// GetRequest names an entity by id (object types and permissions are keyed by
// name/id; the facade routes per RPC).
type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *Actor                 `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{16}
}

func (x *GetRequest) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *GetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *Actor                 `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteRequest) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// EntityResponse returns one entity body as canonical JSON.
type EntityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityJson    string                 `protobuf:"bytes,1,opt,name=entity_json,json=entityJson,proto3" json:"entity_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityResponse) Reset() {
	*x = EntityResponse{}
	mi := &file_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityResponse) ProtoMessage() {}

func (x *EntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityResponse.ProtoReflect.Descriptor instead.
func (*EntityResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{18}
}

func (x *EntityResponse) GetEntityJson() string {
	if x != nil {
		return x.EntityJson
	}
	return ""
}

// EntityListResponse returns a list of entity bodies, each as canonical JSON.
type EntityListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntitiesJson  []string               `protobuf:"bytes,1,rep,name=entities_json,json=entitiesJson,proto3" json:"entities_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityListResponse) Reset() {
	*x = EntityListResponse{}
	mi := &file_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityListResponse) ProtoMessage() {}

func (x *EntityListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityListResponse.ProtoReflect.Descriptor instead.
func (*EntityListResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{19}
}

func (x *EntityListResponse) GetEntitiesJson() []string {
	if x != nil {
		return x.EntitiesJson
	}
	return nil
}

type MembershipKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *Actor                 `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	PrincipalId   string                 `protobuf:"bytes,2,opt,name=principal_id,json=principalId,proto3" json:"principal_id,omitempty"`
	AccountId     string                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MembershipKeyRequest) Reset() {
	*x = MembershipKeyRequest{}
	mi := &file_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembershipKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembershipKeyRequest) ProtoMessage() {}

func (x *MembershipKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembershipKeyRequest.ProtoReflect.Descriptor instead.
func (*MembershipKeyRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{20}
}

func (x *MembershipKeyRequest) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *MembershipKeyRequest) GetPrincipalId() string {
	if x != nil {
		return x.PrincipalId
	}
	return ""
}

func (x *MembershipKeyRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type ListGrantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *Actor                 `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGrantsRequest) Reset() {
	*x = ListGrantsRequest{}
	mi := &file_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGrantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGrantsRequest) ProtoMessage() {}

func (x *ListGrantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGrantsRequest.ProtoReflect.Descriptor instead.
func (*ListGrantsRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{21}
}

func (x *ListGrantsRequest) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *ListGrantsRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

// TemplateKeyRequest names a template by (name, version). version <= 0 selects
// the latest version for Get, and deletes every version for Delete.
type TemplateKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *Actor                 `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       int32                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateKeyRequest) Reset() {
	*x = TemplateKeyRequest{}
	mi := &file_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateKeyRequest) ProtoMessage() {}

func (x *TemplateKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateKeyRequest.ProtoReflect.Descriptor instead.
func (*TemplateKeyRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{22}
}

func (x *TemplateKeyRequest) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *TemplateKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TemplateKeyRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// ApplyTemplateRequest applies template (name, version) into account, filling
// the declared parameters with params and prefixing generated grant ids with
// grant_id_prefix (optional). version <= 0 selects the latest version.
type ApplyTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *Actor                 `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       int32                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Account       string                 `protobuf:"bytes,4,opt,name=account,proto3" json:"account,omitempty"`
	Params        map[string]string      `protobuf:"bytes,5,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	GrantIdPrefix string                 `protobuf:"bytes,6,opt,name=grant_id_prefix,json=grantIdPrefix,proto3" json:"grant_id_prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyTemplateRequest) Reset() {
	*x = ApplyTemplateRequest{}
	mi := &file_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyTemplateRequest) ProtoMessage() {}

func (x *ApplyTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyTemplateRequest.ProtoReflect.Descriptor instead.
func (*ApplyTemplateRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{23}
}

func (x *ApplyTemplateRequest) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *ApplyTemplateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApplyTemplateRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ApplyTemplateRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *ApplyTemplateRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ApplyTemplateRequest) GetGrantIdPrefix() string {
	if x != nil {
		return x.GrantIdPrefix
	}
	return ""
}

type BulkGrantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *Actor                 `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	GrantsJson    []string               `protobuf:"bytes,2,rep,name=grants_json,json=grantsJson,proto3" json:"grants_json,omitempty"` // each a model.Grant as canonical JSON
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkGrantsRequest) Reset() {
	*x = BulkGrantsRequest{}
	mi := &file_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkGrantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkGrantsRequest) ProtoMessage() {}

func (x *BulkGrantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkGrantsRequest.ProtoReflect.Descriptor instead.
func (*BulkGrantsRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{24}
}

func (x *BulkGrantsRequest) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *BulkGrantsRequest) GetGrantsJson() []string {
	if x != nil {
		return x.GrantsJson
	}
	return nil
}

type BulkDeleteGrantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *Actor                 `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	GrantIds      []string               `protobuf:"bytes,2,rep,name=grant_ids,json=grantIds,proto3" json:"grant_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkDeleteGrantsRequest) Reset() {
	*x = BulkDeleteGrantsRequest{}
	mi := &file_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkDeleteGrantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkDeleteGrantsRequest) ProtoMessage() {}

func (x *BulkDeleteGrantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkDeleteGrantsRequest.ProtoReflect.Descriptor instead.
func (*BulkDeleteGrantsRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{25}
}

func (x *BulkDeleteGrantsRequest) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *BulkDeleteGrantsRequest) GetGrantIds() []string {
	if x != nil {
		return x.GrantIds
	}
	return nil
}

// ExportRequest carries only the actor; the whole model is read out. On the
// Twirp surface the principal is the authenticated identity; actor.account is
// where the system-admin authority is resolved.
type ExportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *Actor                 `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportRequest) Reset() {
	*x = ExportRequest{}
	mi := &file_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportRequest) ProtoMessage() {}

func (x *ExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportRequest.ProtoReflect.Descriptor instead.
func (*ExportRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{26}
}

func (x *ExportRequest) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

// ExportResponse returns the whole model as one declarative state file, encoded
// as canonical JSON (the seed.Document shape).
type ExportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentJson  string                 `protobuf:"bytes,1,opt,name=document_json,json=documentJson,proto3" json:"document_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportResponse) Reset() {
	*x = ExportResponse{}
	mi := &file_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportResponse) ProtoMessage() {}

func (x *ExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportResponse.ProtoReflect.Descriptor instead.
func (*ExportResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{27}
}

func (x *ExportResponse) GetDocumentJson() string {
	if x != nil {
		return x.DocumentJson
	}
	return ""
}

// ImportRequest applies a declarative state file (document_json, the
// seed.Document shape as JSON) as an idempotent transactional upsert.
type ImportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *Actor                 `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	DocumentJson  string                 `protobuf:"bytes,2,opt,name=document_json,json=documentJson,proto3" json:"document_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportRequest) Reset() {
	*x = ImportRequest{}
	mi := &file_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportRequest) ProtoMessage() {}

func (x *ImportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportRequest.ProtoReflect.Descriptor instead.
func (*ImportRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{28}
}

func (x *ImportRequest) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *ImportRequest) GetDocumentJson() string {
	if x != nil {
		return x.DocumentJson
	}
	return ""
}

type BestowRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// delegator is the principal bestowing; on the Twirp surface it is overridden
	// by the authenticated identity. grant_json is the model.Grant to bestow.
	Delegator     string `protobuf:"bytes,1,opt,name=delegator,proto3" json:"delegator,omitempty"`
	GrantJson     string `protobuf:"bytes,2,opt,name=grant_json,json=grantJson,proto3" json:"grant_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BestowRequest) Reset() {
	*x = BestowRequest{}
	mi := &file_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BestowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BestowRequest) ProtoMessage() {}

func (x *BestowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BestowRequest.ProtoReflect.Descriptor instead.
func (*BestowRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{29}
}

func (x *BestowRequest) GetDelegator() string {
	if x != nil {
		return x.Delegator
	}
	return ""
}

func (x *BestowRequest) GetGrantJson() string {
	if x != nil {
		return x.GrantJson
	}
	return ""
}

type RevokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delegator     string                 `protobuf:"bytes,1,opt,name=delegator,proto3" json:"delegator,omitempty"`
	GrantId       string                 `protobuf:"bytes,2,opt,name=grant_id,json=grantId,proto3" json:"grant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRequest) Reset() {
	*x = RevokeRequest{}
	mi := &file_service_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRequest) ProtoMessage() {}

func (x *RevokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRequest.ProtoReflect.Descriptor instead.
func (*RevokeRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{30}
}

func (x *RevokeRequest) GetDelegator() string {
	if x != nil {
		return x.Delegator
	}
	return ""
}

func (x *RevokeRequest) GetGrantId() string {
	if x != nil {
		return x.GrantId
	}
	return ""
}

type ImpersonationStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operator      string                 `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Account       string                 `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	Mode          string                 `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"` // "augment" | "become"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImpersonationStartRequest) Reset() {
	*x = ImpersonationStartRequest{}
	mi := &file_service_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImpersonationStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImpersonationStartRequest) ProtoMessage() {}

func (x *ImpersonationStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImpersonationStartRequest.ProtoReflect.Descriptor instead.
func (*ImpersonationStartRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{31}
}

func (x *ImpersonationStartRequest) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *ImpersonationStartRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ImpersonationStartRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *ImpersonationStartRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type ImpersonationSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RealActor     string                 `protobuf:"bytes,1,opt,name=real_actor,json=realActor,proto3" json:"real_actor,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Account       string                 `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	Mode          string                 `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`
	StartedAt     string                 `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"` // RFC3339
	ExpiresAt     string                 `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // RFC3339
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImpersonationSession) Reset() {
	*x = ImpersonationSession{}
	mi := &file_service_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImpersonationSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImpersonationSession) ProtoMessage() {}

func (x *ImpersonationSession) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImpersonationSession.ProtoReflect.Descriptor instead.
func (*ImpersonationSession) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{32}
}

func (x *ImpersonationSession) GetRealActor() string {
	if x != nil {
		return x.RealActor
	}
	return ""
}

func (x *ImpersonationSession) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *ImpersonationSession) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *ImpersonationSession) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *ImpersonationSession) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *ImpersonationSession) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type ImpersonationStopRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Operator string                 `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	// The session being discarded, echoed for symmetry/audit; impersonation
	// sessions are stateless time-boxed values, so stop is a client-side discard.
	Session       *ImpersonationSession `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImpersonationStopRequest) Reset() {
	*x = ImpersonationStopRequest{}
	mi := &file_service_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImpersonationStopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImpersonationStopRequest) ProtoMessage() {}

func (x *ImpersonationStopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImpersonationStopRequest.ProtoReflect.Descriptor instead.
func (*ImpersonationStopRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{33}
}

func (x *ImpersonationStopRequest) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *ImpersonationStopRequest) GetSession() *ImpersonationSession {
	if x != nil {
		return x.Session
	}
	return nil
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\baperture\"\a\n" +
	"\x05Empty\"?\n" +
	"\x05Actor\x12\x1c\n" +
	"\tprincipal\x18\x01 \x01(\tR\tprincipal\x12\x18\n" +
	"\aaccount\x18\x02 \x01(\tR\aaccount\"v\n" +
	"\fCheckRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1c\n" +
	"\tprincipal\x18\x02 \x01(\tR\tprincipal\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x16\n" +
	"\x06object\x18\x04 \x01(\tR\x06object\"f\n" +
	"\bDecision\x12\x14\n" +
	"\x05allow\x18\x01 \x01(\bR\x05allow\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12,\n" +
	"\x12deciding_grant_ids\x18\x03 \x03(\tR\x10decidingGrantIds\"E\n" +
	"\x11CheckBatchRequest\x120\n" +
	"\aqueries\x18\x01 \x03(\v2\x16.aperture.CheckRequestR\aqueries\"\x83\x01\n" +
	"\rBatchDecision\x12.\n" +
	"\bdecision\x18\x01 \x01(\v2\x12.aperture.DecisionR\bdecision\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"G\n" +
	"\x12CheckBatchResponse\x121\n" +
	"\aresults\x18\x01 \x03(\v2\x17.aperture.BatchDecisionR\aresults\"\x92\x01\n" +
	"\x10EnumerateRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1c\n" +
	"\tprincipal\x18\x02 \x01(\tR\tprincipal\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x18\n" +
	"\apattern\x18\x04 \x01(\tR\apattern\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"2\n" +
	"\x11EnumerateResponse\x12\x1d\n" +
	"\n" +
	"object_ids\x18\x01 \x03(\tR\tobjectIds\"M\n" +
	"\x15EnumerateBatchRequest\x124\n" +
	"\aqueries\x18\x01 \x03(\v2\x1a.aperture.EnumerateRequestR\aqueries\"u\n" +
	"\x10BatchEnumeration\x12\x1d\n" +
	"\n" +
	"object_ids\x18\x01 \x03(\tR\tobjectIds\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"N\n" +
	"\x16EnumerateBatchResponse\x124\n" +
	"\aresults\x18\x01 \x03(\v2\x1a.aperture.BatchEnumerationR\aresults\"0\n" +
	"\x0fExplainResponse\x12\x1d\n" +
	"\n" +
	"trace_json\x18\x01 \x01(\tR\ttraceJson\"o\n" +
	"\n" +
	"BatchTrace\x12\x1d\n" +
	"\n" +
	"trace_json\x18\x01 \x01(\tR\ttraceJson\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"F\n" +
	"\x14ExplainBatchResponse\x12.\n" +
	"\aresults\x18\x01 \x03(\v2\x14.aperture.BatchTraceR\aresults\"W\n" +
	"\rEntityRequest\x12%\n" +
	"\x05actor\x18\x01 \x01(\v2\x0f.aperture.ActorR\x05actor\x12\x1f\n" +
	"\ventity_json\x18\x02 \x01(\tR\n" +
	"entityJson\"C\n" +
	"\n" +
	"GetRequest\x12%\n" +
	"\x05actor\x18\x01 \x01(\v2\x0f.aperture.ActorR\x05actor\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"F\n" +
	"\rDeleteRequest\x12%\n" +
	"\x05actor\x18\x01 \x01(\v2\x0f.aperture.ActorR\x05actor\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"1\n" +
	"\x0eEntityResponse\x12\x1f\n" +
	"\ventity_json\x18\x01 \x01(\tR\n" +
	"entityJson\"9\n" +
	"\x12EntityListResponse\x12#\n" +
	"\rentities_json\x18\x01 \x03(\tR\fentitiesJson\"\x7f\n" +
	"\x14MembershipKeyRequest\x12%\n" +
	"\x05actor\x18\x01 \x01(\v2\x0f.aperture.ActorR\x05actor\x12!\n" +
	"\fprincipal_id\x18\x02 \x01(\tR\vprincipalId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\"Y\n" +
	"\x11ListGrantsRequest\x12%\n" +
	"\x05actor\x18\x01 \x01(\v2\x0f.aperture.ActorR\x05actor\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\"i\n" +
	"\x12TemplateKeyRequest\x12%\n" +
	"\x05actor\x18\x01 \x01(\v2\x0f.aperture.ActorR\x05actor\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\"\xac\x02\n" +
	"\x14ApplyTemplateRequest\x12%\n" +
	"\x05actor\x18\x01 \x01(\v2\x0f.aperture.ActorR\x05actor\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\x12\x18\n" +
	"\aaccount\x18\x04 \x01(\tR\aaccount\x12B\n" +
	"\x06params\x18\x05 \x03(\v2*.aperture.ApplyTemplateRequest.ParamsEntryR\x06params\x12&\n" +
	"\x0fgrant_id_prefix\x18\x06 \x01(\tR\rgrantIdPrefix\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"[\n" +
	"\x11BulkGrantsRequest\x12%\n" +
	"\x05actor\x18\x01 \x01(\v2\x0f.aperture.ActorR\x05actor\x12\x1f\n" +
	"\vgrants_json\x18\x02 \x03(\tR\n" +
	"grantsJson\"]\n" +
	"\x17BulkDeleteGrantsRequest\x12%\n" +
	"\x05actor\x18\x01 \x01(\v2\x0f.aperture.ActorR\x05actor\x12\x1b\n" +
	"\tgrant_ids\x18\x02 \x03(\tR\bgrantIds\"6\n" +
	"\rExportRequest\x12%\n" +
	"\x05actor\x18\x01 \x01(\v2\x0f.aperture.ActorR\x05actor\"5\n" +
	"\x0eExportResponse\x12#\n" +
	"\rdocument_json\x18\x01 \x01(\tR\fdocumentJson\"[\n" +
	"\rImportRequest\x12%\n" +
	"\x05actor\x18\x01 \x01(\v2\x0f.aperture.ActorR\x05actor\x12#\n" +
	"\rdocument_json\x18\x02 \x01(\tR\fdocumentJson\"L\n" +
	"\rBestowRequest\x12\x1c\n" +
	"\tdelegator\x18\x01 \x01(\tR\tdelegator\x12\x1d\n" +
	"\n" +
	"grant_json\x18\x02 \x01(\tR\tgrantJson\"H\n" +
	"\rRevokeRequest\x12\x1c\n" +
	"\tdelegator\x18\x01 \x01(\tR\tdelegator\x12\x19\n" +
	"\bgrant_id\x18\x02 \x01(\tR\agrantId\"}\n" +
	"\x19ImpersonationStartRequest\x12\x1a\n" +
	"\boperator\x18\x01 \x01(\tR\boperator\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x18\n" +
	"\aaccount\x18\x03 \x01(\tR\aaccount\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\"\xbb\x01\n" +
	"\x14ImpersonationSession\x12\x1d\n" +
	"\n" +
	"real_actor\x18\x01 \x01(\tR\trealActor\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x18\n" +
	"\aaccount\x18\x03 \x01(\tR\aaccount\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\x12\x1d\n" +
	"\n" +
	"started_at\x18\x05 \x01(\tR\tstartedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\tR\texpiresAt\"p\n" +
	"\x18ImpersonationStopRequest\x12\x1a\n" +
	"\boperator\x18\x01 \x01(\tR\boperator\x128\n" +
	"\asession\x18\x02 \x01(\v2\x1e.aperture.ImpersonationSessionR\asession2\xaa\x18\n" +
	"\x0fApertureService\x123\n" +
	"\x05Check\x12\x16.aperture.CheckRequest\x1a\x12.aperture.Decision\x12G\n" +
	"\n" +
	"CheckBatch\x12\x1b.aperture.CheckBatchRequest\x1a\x1c.aperture.CheckBatchResponse\x12D\n" +
	"\tEnumerate\x12\x1a.aperture.EnumerateRequest\x1a\x1b.aperture.EnumerateResponse\x12S\n" +
	"\x0eEnumerateBatch\x12\x1f.aperture.EnumerateBatchRequest\x1a .aperture.EnumerateBatchResponse\x12<\n" +
	"\aExplain\x12\x16.aperture.CheckRequest\x1a\x19.aperture.ExplainResponse\x12K\n" +
	"\fExplainBatch\x12\x1b.aperture.CheckBatchRequest\x1a\x1e.aperture.ExplainBatchResponse\x129\n" +
	"\rPutObjectType\x12\x17.aperture.EntityRequest\x1a\x0f.aperture.Empty\x12?\n" +
	"\rGetObjectType\x12\x14.aperture.GetRequest\x1a\x18.aperture.EntityResponse\x12@\n" +
	"\x0fListObjectTypes\x12\x0f.aperture.Empty\x1a\x1c.aperture.EntityListResponse\x12<\n" +
	"\x10DeleteObjectType\x12\x17.aperture.DeleteRequest\x1a\x0f.aperture.Empty\x129\n" +
	"\rPutPermission\x12\x17.aperture.EntityRequest\x1a\x0f.aperture.Empty\x12?\n" +
	"\rGetPermission\x12\x14.aperture.GetRequest\x1a\x18.aperture.EntityResponse\x12@\n" +
	"\x0fListPermissions\x12\x0f.aperture.Empty\x1a\x1c.aperture.EntityListResponse\x12<\n" +
	"\x10DeletePermission\x12\x17.aperture.DeleteRequest\x1a\x0f.aperture.Empty\x128\n" +
	"\fPutPrincipal\x12\x17.aperture.EntityRequest\x1a\x0f.aperture.Empty\x12>\n" +
	"\fGetPrincipal\x12\x14.aperture.GetRequest\x1a\x18.aperture.EntityResponse\x12?\n" +
	"\x0eListPrincipals\x12\x0f.aperture.Empty\x1a\x1c.aperture.EntityListResponse\x12;\n" +
	"\x0fDeletePrincipal\x12\x17.aperture.DeleteRequest\x1a\x0f.aperture.Empty\x123\n" +
	"\aPutRole\x12\x17.aperture.EntityRequest\x1a\x0f.aperture.Empty\x129\n" +
	"\aGetRole\x12\x14.aperture.GetRequest\x1a\x18.aperture.EntityResponse\x12:\n" +
	"\tListRoles\x12\x0f.aperture.Empty\x1a\x1c.aperture.EntityListResponse\x126\n" +
	"\n" +
	"DeleteRole\x12\x17.aperture.DeleteRequest\x1a\x0f.aperture.Empty\x124\n" +
	"\bPutGroup\x12\x17.aperture.EntityRequest\x1a\x0f.aperture.Empty\x12:\n" +
	"\bGetGroup\x12\x14.aperture.GetRequest\x1a\x18.aperture.EntityResponse\x12;\n" +
	"\n" +
	"ListGroups\x12\x0f.aperture.Empty\x1a\x1c.aperture.EntityListResponse\x127\n" +
	"\vDeleteGroup\x12\x17.aperture.DeleteRequest\x1a\x0f.aperture.Empty\x126\n" +
	"\n" +
	"PutAccount\x12\x17.aperture.EntityRequest\x1a\x0f.aperture.Empty\x12<\n" +
	"\n" +
	"GetAccount\x12\x14.aperture.GetRequest\x1a\x18.aperture.EntityResponse\x12=\n" +
	"\fListAccounts\x12\x0f.aperture.Empty\x1a\x1c.aperture.EntityListResponse\x129\n" +
	"\rDeleteAccount\x12\x17.aperture.DeleteRequest\x1a\x0f.aperture.Empty\x129\n" +
	"\rPutMembership\x12\x17.aperture.EntityRequest\x1a\x0f.aperture.Empty\x12C\n" +
	"\x10DeleteMembership\x12\x1e.aperture.MembershipKeyRequest\x1a\x0f.aperture.Empty\x124\n" +
	"\bPutGrant\x12\x17.aperture.EntityRequest\x1a\x0f.aperture.Empty\x12:\n" +
	"\bGetGrant\x12\x14.aperture.GetRequest\x1a\x18.aperture.EntityResponse\x12G\n" +
	"\n" +
	"ListGrants\x12\x1b.aperture.ListGrantsRequest\x1a\x1c.aperture.EntityListResponse\x127\n" +
	"\vDeleteGrant\x12\x17.aperture.DeleteRequest\x1a\x0f.aperture.Empty\x127\n" +
	"\vPutTemplate\x12\x17.aperture.EntityRequest\x1a\x0f.aperture.Empty\x12E\n" +
	"\vGetTemplate\x12\x1c.aperture.TemplateKeyRequest\x1a\x18.aperture.EntityResponse\x12>\n" +
	"\rListTemplates\x12\x0f.aperture.Empty\x1a\x1c.aperture.EntityListResponse\x12?\n" +
	"\x0eDeleteTemplate\x12\x1c.aperture.TemplateKeyRequest\x1a\x0f.aperture.Empty\x12M\n" +
	"\rApplyTemplate\x12\x1e.aperture.ApplyTemplateRequest\x1a\x1c.aperture.EntityListResponse\x12=\n" +
	"\rBulkPutGrants\x12\x1b.aperture.BulkGrantsRequest\x1a\x0f.aperture.Empty\x12F\n" +
	"\x10BulkDeleteGrants\x12!.aperture.BulkDeleteGrantsRequest\x1a\x0f.aperture.Empty\x12;\n" +
	"\x06Export\x12\x17.aperture.ExportRequest\x1a\x18.aperture.ExportResponse\x122\n" +
	"\x06Import\x12\x17.aperture.ImportRequest\x1a\x0f.aperture.Empty\x122\n" +
	"\x06Bestow\x12\x17.aperture.BestowRequest\x1a\x0f.aperture.Empty\x122\n" +
	"\x06Revoke\x12\x17.aperture.RevokeRequest\x1a\x0f.aperture.Empty\x12Y\n" +
	"\x12ImpersonationStart\x12#.aperture.ImpersonationStartRequest\x1a\x1e.aperture.ImpersonationSession\x12H\n" +
	"\x11ImpersonationStop\x12\".aperture.ImpersonationStopRequest\x1a\x0f.aperture.EmptyB3Z1github.com/frankbardon/aperture/internal/wire/rpcb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_service_proto_goTypes = []any{
	(*Empty)(nil),                     // 0: aperture.Empty
	(*Actor)(nil),                     // 1: aperture.Actor
	(*CheckRequest)(nil),              // 2: aperture.CheckRequest
	(*Decision)(nil),                  // 3: aperture.Decision
	(*CheckBatchRequest)(nil),         // 4: aperture.CheckBatchRequest
	(*BatchDecision)(nil),             // 5: aperture.BatchDecision
	(*CheckBatchResponse)(nil),        // 6: aperture.CheckBatchResponse
	(*EnumerateRequest)(nil),          // 7: aperture.EnumerateRequest
	(*EnumerateResponse)(nil),         // 8: aperture.EnumerateResponse
	(*EnumerateBatchRequest)(nil),     // 9: aperture.EnumerateBatchRequest
	(*BatchEnumeration)(nil),          // 10: aperture.BatchEnumeration
	(*EnumerateBatchResponse)(nil),    // 11: aperture.EnumerateBatchResponse
	(*ExplainResponse)(nil),           // 12: aperture.ExplainResponse
	(*BatchTrace)(nil),                // 13: aperture.BatchTrace
	(*ExplainBatchResponse)(nil),      // 14: aperture.ExplainBatchResponse
	(*EntityRequest)(nil),             // 15: aperture.EntityRequest
	(*GetRequest)(nil),                // 16: aperture.GetRequest
	(*DeleteRequest)(nil),             // 17: aperture.DeleteRequest
	(*EntityResponse)(nil),            // 18: aperture.EntityResponse
	(*EntityListResponse)(nil),        // 19: aperture.EntityListResponse
	(*MembershipKeyRequest)(nil),      // 20: aperture.MembershipKeyRequest
	(*ListGrantsRequest)(nil),         // 21: aperture.ListGrantsRequest
	(*TemplateKeyRequest)(nil),        // 22: aperture.TemplateKeyRequest
	(*ApplyTemplateRequest)(nil),      // 23: aperture.ApplyTemplateRequest
	(*BulkGrantsRequest)(nil),         // 24: aperture.BulkGrantsRequest
	(*BulkDeleteGrantsRequest)(nil),   // 25: aperture.BulkDeleteGrantsRequest
	(*ExportRequest)(nil),             // 26: aperture.ExportRequest
	(*ExportResponse)(nil),            // 27: aperture.ExportResponse
	(*ImportRequest)(nil),             // 28: aperture.ImportRequest
	(*BestowRequest)(nil),             // 29: aperture.BestowRequest
	(*RevokeRequest)(nil),             // 30: aperture.RevokeRequest
	(*ImpersonationStartRequest)(nil), // 31: aperture.ImpersonationStartRequest
	(*ImpersonationSession)(nil),      // 32: aperture.ImpersonationSession
	(*ImpersonationStopRequest)(nil),  // 33: aperture.ImpersonationStopRequest
	nil,                               // 34: aperture.ApplyTemplateRequest.ParamsEntry
}
var file_service_proto_depIdxs = []int32{
	2,  // 0: aperture.CheckBatchRequest.queries:type_name -> aperture.CheckRequest
	3,  // 1: aperture.BatchDecision.decision:type_name -> aperture.Decision
	5,  // 2: aperture.CheckBatchResponse.results:type_name -> aperture.BatchDecision
	7,  // 3: aperture.EnumerateBatchRequest.queries:type_name -> aperture.EnumerateRequest
	10, // 4: aperture.EnumerateBatchResponse.results:type_name -> aperture.BatchEnumeration
	13, // 5: aperture.ExplainBatchResponse.results:type_name -> aperture.BatchTrace
	1,  // 6: aperture.EntityRequest.actor:type_name -> aperture.Actor
	1,  // 7: aperture.GetRequest.actor:type_name -> aperture.Actor
	1,  // 8: aperture.DeleteRequest.actor:type_name -> aperture.Actor
	1,  // 9: aperture.MembershipKeyRequest.actor:type_name -> aperture.Actor
	1,  // 10: aperture.ListGrantsRequest.actor:type_name -> aperture.Actor
	1,  // 11: aperture.TemplateKeyRequest.actor:type_name -> aperture.Actor
	1,  // 12: aperture.ApplyTemplateRequest.actor:type_name -> aperture.Actor
	34, // 13: aperture.ApplyTemplateRequest.params:type_name -> aperture.ApplyTemplateRequest.ParamsEntry
	1,  // 14: aperture.BulkGrantsRequest.actor:type_name -> aperture.Actor
	1,  // 15: aperture.BulkDeleteGrantsRequest.actor:type_name -> aperture.Actor
	1,  // 16: aperture.ExportRequest.actor:type_name -> aperture.Actor
	1,  // 17: aperture.ImportRequest.actor:type_name -> aperture.Actor
	32, // 18: aperture.ImpersonationStopRequest.session:type_name -> aperture.ImpersonationSession
	2,  // 19: aperture.ApertureService.Check:input_type -> aperture.CheckRequest
	4,  // 20: aperture.ApertureService.CheckBatch:input_type -> aperture.CheckBatchRequest
	7,  // 21: aperture.ApertureService.Enumerate:input_type -> aperture.EnumerateRequest
	9,  // 22: aperture.ApertureService.EnumerateBatch:input_type -> aperture.EnumerateBatchRequest
	2,  // 23: aperture.ApertureService.Explain:input_type -> aperture.CheckRequest
	4,  // 24: aperture.ApertureService.ExplainBatch:input_type -> aperture.CheckBatchRequest
	15, // 25: aperture.ApertureService.PutObjectType:input_type -> aperture.EntityRequest
	16, // 26: aperture.ApertureService.GetObjectType:input_type -> aperture.GetRequest
	0,  // 27: aperture.ApertureService.ListObjectTypes:input_type -> aperture.Empty
	17, // 28: aperture.ApertureService.DeleteObjectType:input_type -> aperture.DeleteRequest
	15, // 29: aperture.ApertureService.PutPermission:input_type -> aperture.EntityRequest
	16, // 30: aperture.ApertureService.GetPermission:input_type -> aperture.GetRequest
	0,  // 31: aperture.ApertureService.ListPermissions:input_type -> aperture.Empty
	17, // 32: aperture.ApertureService.DeletePermission:input_type -> aperture.DeleteRequest
	15, // 33: aperture.ApertureService.PutPrincipal:input_type -> aperture.EntityRequest
	16, // 34: aperture.ApertureService.GetPrincipal:input_type -> aperture.GetRequest
	0,  // 35: aperture.ApertureService.ListPrincipals:input_type -> aperture.Empty
	17, // 36: aperture.ApertureService.DeletePrincipal:input_type -> aperture.DeleteRequest
	15, // 37: aperture.ApertureService.PutRole:input_type -> aperture.EntityRequest
	16, // 38: aperture.ApertureService.GetRole:input_type -> aperture.GetRequest
	0,  // 39: aperture.ApertureService.ListRoles:input_type -> aperture.Empty
	17, // 40: aperture.ApertureService.DeleteRole:input_type -> aperture.DeleteRequest
	15, // 41: aperture.ApertureService.PutGroup:input_type -> aperture.EntityRequest
	16, // 42: aperture.ApertureService.GetGroup:input_type -> aperture.GetRequest
	0,  // 43: aperture.ApertureService.ListGroups:input_type -> aperture.Empty
	17, // 44: aperture.ApertureService.DeleteGroup:input_type -> aperture.DeleteRequest
	15, // 45: aperture.ApertureService.PutAccount:input_type -> aperture.EntityRequest
	16, // 46: aperture.ApertureService.GetAccount:input_type -> aperture.GetRequest
	0,  // 47: aperture.ApertureService.ListAccounts:input_type -> aperture.Empty
	17, // 48: aperture.ApertureService.DeleteAccount:input_type -> aperture.DeleteRequest
	15, // 49: aperture.ApertureService.PutMembership:input_type -> aperture.EntityRequest
	20, // 50: aperture.ApertureService.DeleteMembership:input_type -> aperture.MembershipKeyRequest
	15, // 51: aperture.ApertureService.PutGrant:input_type -> aperture.EntityRequest
	16, // 52: aperture.ApertureService.GetGrant:input_type -> aperture.GetRequest
	21, // 53: aperture.ApertureService.ListGrants:input_type -> aperture.ListGrantsRequest
	17, // 54: aperture.ApertureService.DeleteGrant:input_type -> aperture.DeleteRequest
	15, // 55: aperture.ApertureService.PutTemplate:input_type -> aperture.EntityRequest
	22, // 56: aperture.ApertureService.GetTemplate:input_type -> aperture.TemplateKeyRequest
	0,  // 57: aperture.ApertureService.ListTemplates:input_type -> aperture.Empty
	22, // 58: aperture.ApertureService.DeleteTemplate:input_type -> aperture.TemplateKeyRequest
	23, // 59: aperture.ApertureService.ApplyTemplate:input_type -> aperture.ApplyTemplateRequest
	24, // 60: aperture.ApertureService.BulkPutGrants:input_type -> aperture.BulkGrantsRequest
	25, // 61: aperture.ApertureService.BulkDeleteGrants:input_type -> aperture.BulkDeleteGrantsRequest
	26, // 62: aperture.ApertureService.Export:input_type -> aperture.ExportRequest
	28, // 63: aperture.ApertureService.Import:input_type -> aperture.ImportRequest
	29, // 64: aperture.ApertureService.Bestow:input_type -> aperture.BestowRequest
	30, // 65: aperture.ApertureService.Revoke:input_type -> aperture.RevokeRequest
	31, // 66: aperture.ApertureService.ImpersonationStart:input_type -> aperture.ImpersonationStartRequest
	33, // 67: aperture.ApertureService.ImpersonationStop:input_type -> aperture.ImpersonationStopRequest
	3,  // 68: aperture.ApertureService.Check:output_type -> aperture.Decision
	6,  // 69: aperture.ApertureService.CheckBatch:output_type -> aperture.CheckBatchResponse
	8,  // 70: aperture.ApertureService.Enumerate:output_type -> aperture.EnumerateResponse
	11, // 71: aperture.ApertureService.EnumerateBatch:output_type -> aperture.EnumerateBatchResponse
	12, // 72: aperture.ApertureService.Explain:output_type -> aperture.ExplainResponse
	14, // 73: aperture.ApertureService.ExplainBatch:output_type -> aperture.ExplainBatchResponse
	0,  // 74: aperture.ApertureService.PutObjectType:output_type -> aperture.Empty
	18, // 75: aperture.ApertureService.GetObjectType:output_type -> aperture.EntityResponse
	19, // 76: aperture.ApertureService.ListObjectTypes:output_type -> aperture.EntityListResponse
	0,  // 77: aperture.ApertureService.DeleteObjectType:output_type -> aperture.Empty
	0,  // 78: aperture.ApertureService.PutPermission:output_type -> aperture.Empty
	18, // 79: aperture.ApertureService.GetPermission:output_type -> aperture.EntityResponse
	19, // 80: aperture.ApertureService.ListPermissions:output_type -> aperture.EntityListResponse
	0,  // 81: aperture.ApertureService.DeletePermission:output_type -> aperture.Empty
	0,  // 82: aperture.ApertureService.PutPrincipal:output_type -> aperture.Empty
	18, // 83: aperture.ApertureService.GetPrincipal:output_type -> aperture.EntityResponse
	19, // 84: aperture.ApertureService.ListPrincipals:output_type -> aperture.EntityListResponse
	0,  // 85: aperture.ApertureService.DeletePrincipal:output_type -> aperture.Empty
	0,  // 86: aperture.ApertureService.PutRole:output_type -> aperture.Empty
	18, // 87: aperture.ApertureService.GetRole:output_type -> aperture.EntityResponse
	19, // 88: aperture.ApertureService.ListRoles:output_type -> aperture.EntityListResponse
	0,  // 89: aperture.ApertureService.DeleteRole:output_type -> aperture.Empty
	0,  // 90: aperture.ApertureService.PutGroup:output_type -> aperture.Empty
	18, // 91: aperture.ApertureService.GetGroup:output_type -> aperture.EntityResponse
	19, // 92: aperture.ApertureService.ListGroups:output_type -> aperture.EntityListResponse
	0,  // 93: aperture.ApertureService.DeleteGroup:output_type -> aperture.Empty
	0,  // 94: aperture.ApertureService.PutAccount:output_type -> aperture.Empty
	18, // 95: aperture.ApertureService.GetAccount:output_type -> aperture.EntityResponse
	19, // 96: aperture.ApertureService.ListAccounts:output_type -> aperture.EntityListResponse
	0,  // 97: aperture.ApertureService.DeleteAccount:output_type -> aperture.Empty
	0,  // 98: aperture.ApertureService.PutMembership:output_type -> aperture.Empty
	0,  // 99: aperture.ApertureService.DeleteMembership:output_type -> aperture.Empty
	0,  // 100: aperture.ApertureService.PutGrant:output_type -> aperture.Empty
	18, // 101: aperture.ApertureService.GetGrant:output_type -> aperture.EntityResponse
	19, // 102: aperture.ApertureService.ListGrants:output_type -> aperture.EntityListResponse
	0,  // 103: aperture.ApertureService.DeleteGrant:output_type -> aperture.Empty
	0,  // 104: aperture.ApertureService.PutTemplate:output_type -> aperture.Empty
	18, // 105: aperture.ApertureService.GetTemplate:output_type -> aperture.EntityResponse
	19, // 106: aperture.ApertureService.ListTemplates:output_type -> aperture.EntityListResponse
	0,  // 107: aperture.ApertureService.DeleteTemplate:output_type -> aperture.Empty
	19, // 108: aperture.ApertureService.ApplyTemplate:output_type -> aperture.EntityListResponse
	0,  // 109: aperture.ApertureService.BulkPutGrants:output_type -> aperture.Empty
	0,  // 110: aperture.ApertureService.BulkDeleteGrants:output_type -> aperture.Empty
	27, // 111: aperture.ApertureService.Export:output_type -> aperture.ExportResponse
	0,  // 112: aperture.ApertureService.Import:output_type -> aperture.Empty
	0,  // 113: aperture.ApertureService.Bestow:output_type -> aperture.Empty
	0,  // 114: aperture.ApertureService.Revoke:output_type -> aperture.Empty
	32, // 115: aperture.ApertureService.ImpersonationStart:output_type -> aperture.ImpersonationSession
	0,  // 116: aperture.ApertureService.ImpersonationStop:output_type -> aperture.Empty
	68, // [68:117] is the sub-list for method output_type
	19, // [19:68] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
